### ISSUE TITLE
Implement Query Params

### ISSUE THREAD

**Issue by camilamaia** [camilamaia/scanapi#4]
Similar to `headers` implementation

```yaml
api:
  base_url: ${BASE_URL}
  headers:
    Authorization: ${BEARER_TOKEN}
  params:
    per_page: 10
```
