### ISSUE TITLE
Hide sensitive info from headers is not working

### ISSUE THREAD

**Issue by camilamaia** [camilamaia/scanapi#66]
## Description
After the refactor on the reporter templates, hide sensitive info from headers is not working. It shows the real data instead of `"<sensitive information>"`

## How to reproduce

Create a config file `.scanapi.yaml` with the content:
```
docs:
  hide:
    headers:
      - Authorization
```

Run scanapi with this config file and set an Authorization header inside the api specification:

```
api:
  base_url: ${BASE_URL}
  headers:
    Authorization: token123
```

The word `token123` will appear in the report, instead of `"<sensitive information>"`
